<?php
class Lipsum extends CComponent {
	private static $_lipsum;

	private static function setup() {
		self::$_lipsum = array(
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
			'Maecenas eu augue in est porttitor vestibulum sit amet vitae augue.',
			'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
			'Sed interdum ultrices posuere.',
			'Aliquam sodales lacinia mi, sed imperdiet urna tincidunt at.',
			'Quisque non bibendum magna.',
			'Curabitur eget nulla elit, at lacinia magna.',
			'Vestibulum massa purus, convallis ac eleifend in, tristique malesuada odio.',
			'In rhoncus, nisl a faucibus accumsan, purus dolor gravida leo, vitae tincidunt magna tellus vel elit.',
			'Pellentesque molestie congue felis.',
			'Phasellus pellentesque placerat hendrerit.',
			'Quisque in tortor massa.',
			'Vestibulum nunc tortor, ultrices sed congue vitae, scelerisque eu tortor.',
			'Vestibulum molestie suscipit porttitor.',
			'Phasellus ultricies, urna sed tincidunt porta, neque enim congue urna, quis imperdiet metus massa et neque.',
			'Suspendisse sed nisi lectus.', 'Nulla facilisi.',
			'Proin lobortis lorem sed odio fermentum a facilisis nulla fermentum.',
			'Maecenas in imperdiet lorem.',
			'Suspendisse fringilla, odio sed posuere aliquet, ipsum enim cursus lacus, in rutrum ligula ipsum ac felis.',
			'Duis nec nisi eu massa lacinia vulputate id ut orci.',
			'Praesent ut sapien nulla.',
			'Integer tristique, velit in congue pellentesque, odio sapien adipiscing nisi, ultricies vestibulum odio augue non nulla.',
			'Donec orci mauris, adipiscing tempor sollicitudin ac, blandit quis tortor.',
			'Cras lorem sem, blandit a malesuada sed, ultricies a augue.',
			'Nulla pulvinar, enim eget sagittis porttitor, turpis ipsum elementum massa, quis ornare elit velit non lacus.',
			'Aenean aliquet fermentum urna et viverra.',
			'Maecenas lacinia vestibulum laoreet.', 'Ut et placerat ipsum.',
			'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis non lorem a eros vulputate mattis eget eget magna.',
			'Curabitur neque quam, eleifend at vehicula sit amet, imperdiet sed diam.',
			'Aenean eleifend orci egestas metus mattis rhoncus.',
			'Aliquam scelerisque odio eu enim auctor sed sollicitudin metus malesuada.',
			'Cras nisi ipsum, tempor nec mollis nec, aliquet at mi.',
			'Donec blandit, justo eu volutpat euismod, ligula ipsum egestas lacus, congue laoreet enim ipsum non augue.',
			'Quisque faucibus urna quis lacus auctor ornare.',
			'Etiam vel lacus diam.',
			'Curabitur porttitor, sem eu varius venenatis, eros odio volutpat nulla, vel gravida magna lectus ac sapien.',
			'Praesent eu massa sed orci egestas venenatis.',
			'Pellentesque lacinia ligula vitae justo pellentesque tincidunt.',
			'Cras porta aliquet nulla, vel eleifend ante porttitor sit amet.',
			'Nulla facilisis nunc ac magna hendrerit eget blandit tellus sodales.',
			'Nunc et mauris sem.',
			'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi orci enim, sodales in ullamcorper in, tempor nec risus.',
			'Nam sodales, quam eu viverra accumsan, libero nisi suscipit augue, in vulputate ligula enim ac dolor.',
			'Nunc eleifend consequat leo, eu eleifend enim scelerisque ut.',
			'Nullam vitae ligula vitae nulla sollicitudin gravida.',
			'Mauris ullamcorper molestie dui, eget scelerisque nisl gravida sit amet.',
			'Vestibulum sodales mattis turpis eget viverra.',
			'Praesent pharetra aliquet libero, cursus suscipit metus sollicitudin ut.',
			'Nulla lacinia fermentum nibh, et volutpat nisl cursus commodo.',
			'Quisque vitae quam quis odio tincidunt pharetra eu placerat nunc.',
			'Nunc ullamcorper volutpat eros ut consectetur.',
			'Cras pulvinar sodales velit quis malesuada.',
			'Sed vulputate libero in mauris molestie tristique.',
			'Praesent sed sagittis dolor.',
			'Integer at risus vel nisi vulputate molestie.',
			'Curabitur placerat metus nec nisi gravida volutpat.',
			'Vestibulum malesuada sem nec arcu suscipit iaculis.',
			'Vivamus scelerisque sem sed nibh interdum convallis.',
			'Cras ornare porta placerat.', 'Vivamus id tortor purus.',
			'Sed adipiscing, eros non iaculis hendrerit, erat enim tristique est, vestibulum laoreet tortor libero ac lorem.',
			'Cras ultrices mollis nisl, ac elementum diam placerat at.',
			'Proin egestas sollicitudin nulla eu porta.',
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
			'Ut euismod enim ut nisl gravida dapibus vehicula ipsum iaculis.',
			'Suspendisse ut est auctor lacus ultrices posuere.',
			'Integer ac diam vitae tortor fermentum hendrerit.',
			'Mauris elit enim, tempor blandit congue eget, pretium id sapien.',
			'Duis orci purus, posuere at sodales eget, sagittis non risus.',
			'Duis mattis tortor at mauris bibendum congue.',
			'Aenean pretium dolor ut est volutpat convallis.',
			'Suspendisse potenti.',
			'Sed varius tellus eu tellus hendrerit pharetra congue arcu faucibus.',
			'Sed venenatis neque eget ipsum faucibus nec vulputate orci sagittis.',
			'Morbi luctus, massa eu lacinia mattis, quam felis accumsan urna, ut elementum velit ipsum a purus.',
			'Integer tristique ornare lectus, a vehicula felis blandit dapibus.',
			'Vestibulum vitae suscipit risus.', 'Integer porta vulputate euismod.',
			'Etiam pretium tristique massa eget pellentesque.',
			'Aenean faucibus interdum sem, in blandit purus iaculis eu.',
			'Vestibulum pharetra lectus et libero mattis et congue arcu consequat.',
			'Nam justo quam, pulvinar eu consequat malesuada, mattis a ligula.',
			'Praesent tempor tincidunt velit.',
			'Sed odio purus, venenatis nec fringilla id, bibendum et justo.',
			'Donec rhoncus eros eu ante sagittis ut tristique lorem porttitor.',
			'Duis ac libero arcu, vitae lacinia risus.',
			'Ut consequat nunc eu turpis sodales id condimentum ligula luctus.',
			'Duis elit neque, ultricies ut egestas vel, luctus tempor metus.',
			'Proin nisi nisl, malesuada quis lobortis id, vulputate eu sem.',
			'Nullam ac consectetur turpis.', 'Nulla facilisi.',
			'Quisque a diam arcu, a dignissim felis.',
			'Vivamus et dolor nec tellus malesuada viverra.',
			'Quisque accumsan imperdiet lobortis.',
			'Phasellus enim turpis, mollis eu pulvinar eget, tempor sed elit.',
			'Sed pretium lacus magna, nec laoreet erat.',
			'Integer tortor odio, mattis at gravida eget, blandit non quam.',
			'Nulla arcu nisi, adipiscing eu condimentum vitae, tristique at ante.',
			'Maecenas sit amet massa lacus.',
			'Curabitur sem justo, varius non sollicitudin et, accumsan eget neque.',
			'Aenean eget molestie lacus.', 'In in purus eu purus viverra suscipit.',
			'Suspendisse turpis mi, mattis quis vehicula nec, dignissim vel diam.',
			'Curabitur placerat rhoncus turpis, id egestas massa congue nec.',
			'Integer tempus laoreet ligula a congue.',
			'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
			'Nullam ac cursus nibh.',
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
			'Curabitur eleifend ullamcorper orci, non pulvinar justo vehicula quis.',
			'In hac habitasse platea dictumst.',
			'Fusce turpis leo, mattis a pellentesque eget, rhoncus vel tortor.',
			'Proin purus dolor, imperdiet vulputate posuere nec, faucibus vitae nunc.',
			'Sed malesuada, nunc vitae vulputate ultricies, eros est sodales massa, eget bibendum metus eros eu diam.',
			'Nulla facilisi.',
			'Nullam hendrerit facilisis nulla, id ullamcorper dui malesuada vestibulum.',
			'Nulla vel arcu ipsum, a dapibus mauris.',
			'Nullam at tortor nulla, ut accumsan neque.',
			'Proin malesuada justo tempus dui mattis et viverra lectus ullamcorper.',
			'Integer sapien tellus, cursus sed interdum vel, viverra vel nulla.',
			'Etiam nec sapien sem.', 'Nam in est sed diam iaculis convallis.',
			'Donec at libero ut lectus consequat malesuada.',
			'Praesent molestie fermentum metus, feugiat scelerisque nisl suscipit sed.',
			'Duis aliquet dui eu tellus egestas pellentesque.',
			'Mauris vitae nisi suscipit arcu semper pharetra.',
			'Integer eu sapien at diam porttitor iaculis id ut tellus.',
			'Nam ac purus sit amet nulla tincidunt dapibus.',
			'Praesent dignissim neque vitae sapien feugiat ultrices.',
			'Vestibulum semper tempor ipsum, aliquet posuere odio ultrices vel.',
			'Mauris molestie gravida orci, luctus vestibulum est dignissim vitae.',
			'Proin egestas pulvinar est at tristique.',
			'Fusce dui neque, iaculis sit amet tincidunt et, adipiscing in ante.',
			'Nam blandit tortor et quam malesuada et ultricies leo pharetra.',
			'Nunc consequat semper dictum.',
			'In consequat est nec leo lacinia dictum.',
			'In adipiscing consectetur metus, nec condimentum ipsum congue in.',
			'Maecenas lobortis leo vel ligula porttitor viverra quis quis eros.',
			'Nam in tortor eget turpis ornare porta et in quam.',
			'Pellentesque vitae elit eros.',
			'Curabitur semper diam ut orci dictum ut varius risus facilisis.',
			'In non dui non purus convallis blandit.',
			'Maecenas felis justo, suscipit sed interdum at, pharetra id nisi.',
			'Ut eu diam neque, vel tincidunt est.', 'Curabitur vitae nisi ligula.',
			'Vivamus magna risus, vehicula vel laoreet nec, faucibus sit amet dolor.',
			'Duis eu pretium nulla.', 'In sit amet massa nunc, sed euismod massa.',
			'Aenean varius mollis metus, vulputate tincidunt orci tempus quis.',
			'Phasellus vel placerat tellus.',
			'Cras commodo augue nec nibh pharetra feugiat.',
			'Curabitur ut orci tortor.',
			'Nunc ante elit, elementum at pharetra faucibus, imperdiet a risus.',
			'Fusce elementum urna sit amet nunc accumsan lacinia.',
			'Nam eget sapien et enim tincidunt pretium.',
			'Aliquam in sapien augue, volutpat tempor odio.',
			'Nulla sed hendrerit neque.', 'Pellentesque quis mollis tellus.',
			'Nullam massa eros, gravida at rhoncus non, bibendum at diam.',
			'Pellentesque a fringilla ipsum.',
			'Maecenas tristique neque in eros placerat sit amet adipiscing orci egestas.',
			'Fusce molestie placerat nisi vel tincidunt.',
			'Donec sapien leo, rhoncus et pharetra ultricies, egestas et felis.',
			'Cras cursus dignissim dolor, eu venenatis sem lacinia quis.',
			'Vivamus erat tortor, venenatis quis venenatis eget, euismod facilisis tellus.',
			'Donec vehicula erat sed urna porttitor vel fermentum odio vulputate.',
			'Proin auctor ante nec erat venenatis elementum.',
			'Pellentesque nec tortor nulla.',
			'Vivamus convallis, felis at rhoncus lacinia, quam nisl facilisis tortor, eu rutrum arcu massa sit amet neque.',
			'Nulla facilisi.', 'Sed non mauris leo.',
			'Cras quis nulla vitae sapien ullamcorper faucibus.',
			'Curabitur convallis erat ut magna luctus ac dignissim dui accumsan.',
			'Nulla sit amet hendrerit lacus.', 'Maecenas id consectetur ligula.',
			'Etiam scelerisque erat non dolor ultrices vitae ornare arcu gravida.',
			'Duis consequat leo eget sem tincidunt ut blandit odio ultricies.',
			'In consequat placerat lorem eu gravida.',
			'Nullam aliquam sodales lorem, sed consectetur nisl elementum nec.',
			'Mauris arcu sapien, accumsan vestibulum volutpat eget, commodo sit amet tortor.',
			'Suspendisse potenti.',
			'Quisque sit amet dolor quis ligula interdum tristique id quis massa.',
			'Vivamus venenatis ultricies rutrum.',
			'In hendrerit, enim sit amet rutrum mollis, leo enim varius nibh, sit amet cursus tortor libero eget nisi.',
			'Integer at ante ligula.',
			'Suspendisse malesuada, velit ut convallis bibendum, neque sapien ornare nisl, euismod laoreet ante nunc non mi.',
			'Nunc quis sollicitudin odio.',
			'Aenean blandit interdum mi, id malesuada ligula convallis ac.',
			'Quisque aliquet nisl ac felis fermentum lacinia.',
			'Ut tincidunt, urna sed venenatis interdum, lectus quam hendrerit purus, id aliquet urna felis non est.',
			'Vivamus pharetra aliquet lectus et consequat.',
			'Nam dignissim ornare tortor a adipiscing.',
			'Fusce mattis diam id eros commodo nec rutrum enim malesuada.',
			'Pellentesque ullamcorper est id arcu commodo ullamcorper.',
			'In hac habitasse platea dictumst.',
			'Proin fermentum molestie massa, eget sagittis mauris vehicula non.',
			'Etiam sed laoreet nulla.',
			'In rutrum erat at purus dignissim vel egestas turpis iaculis.',
			'Vivamus lobortis faucibus ante vel tristique.',
			'Cras ut arcu eu risus ultricies scelerisque.',
			'Morbi eu libero eu nibh hendrerit semper.',
			'Nam posuere dapibus nulla, ac molestie arcu aliquet sit amet.',
			'Sed ac dolor at mi ultrices tincidunt.',
			'Etiam lacinia varius turpis ac suscipit.',
			'Phasellus scelerisque, eros ut fermentum dignissim, purus leo dapibus sem, sit amet iaculis ipsum est quis tellus.',
			'Sed accumsan egestas turpis, quis tincidunt ante dignissim in.',
			'Duis accumsan, eros sed rutrum ultrices, ipsum nulla aliquam massa, sed imperdiet justo justo eget mi.',
			'Quisque aliquet, magna sit amet tincidunt convallis, justo justo faucibus lacus, nec ornare turpis erat molestie eros.',
			'Aliquam ullamcorper ipsum at tellus pretium id luctus odio congue.',
			'Sed a mauris id ipsum rhoncus suscipit at a ligula.',
			'Aenean mattis euismod turpis nec gravida.',
			'Praesent fermentum faucibus volutpat.',
			'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce non lectus lectus.',
			'Fusce sodales, urna quis facilisis accumsan, nisi lorem faucibus diam, et sagittis enim nulla facilisis dui.',
			'Donec porta facilisis urna at condimentum.',
			'Maecenas magna justo, commodo sed eleifend vitae, pellentesque a quam.',
			'Fusce vitae neque neque, eu ultricies tortor.',
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
			'Sed mattis fringilla vulputate.', 'Nullam in urna massa.',
			'Vestibulum iaculis porttitor lacus nec consequat.',
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
			'Sed et tellus eros.',
			'Proin congue, est non varius cursus, sapien orci congue nisi, venenatis sagittis nulla mauris eu mauris.',
			'Nullam placerat congue urna eget rutrum.',
			'Sed tellus augue, molestie ac faucibus a, pellentesque non est.',
			'Nam quis orci ac purus luctus eleifend et at orci.',
			'Sed malesuada velit non ipsum iaculis euismod.',
			'Aliquam tincidunt, eros vitae facilisis condimentum, tortor mi cursus urna, sit amet facilisis diam mi in turpis.',
			'Proin vel nisl massa.', 'Sed egestas eros leo.',
			'Vestibulum quis leo id velit fermentum euismod ut vitae sapien.',
			'Etiam in quam nec elit elementum mattis.',
			'Aliquam at nisi purus, sit amet aliquet dui.',
			'Aenean et quam at mi aliquet ultricies.', 'Aliquam erat volutpat.',
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
			'Vivamus quis magna id tortor condimentum tempus.', 'Nulla facilisi.',
			'Pellentesque malesuada, mauris sit amet sagittis luctus, libero risus dignissim leo, sed bibendum lacus tortor quis nibh.',
			'Nulla ac consectetur lacus.',
			'Fusce ornare porttitor eros vel tristique.',
			'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
			'Suspendisse dignissim consectetur nisl.',
			'Sed facilisis posuere blandit.',
			'Sed sagittis vestibulum velit eget elementum.',
			'Quisque et nisi arcu.',
			'Vivamus non nisl nunc, eget pellentesque lorem.',
			'Sed fringilla, nibh a gravida gravida, est elit dapibus orci, ultricies commodo enim ipsum ut orci.',
			'Sed rhoncus pharetra quam ut convallis.',
			'Maecenas ac velit vel erat vehicula venenatis.',
			'Quisque feugiat egestas consectetur.',
			'Vestibulum fringilla condimentum nisl et bibendum.',
			'Duis augue elit, facilisis quis pulvinar non, pharetra ac purus.',
			'Sed porta ultricies sem eu gravida.',
			'Aenean iaculis dictum nunc et porttitor.',
			'Ut at dui justo, et lobortis nulla.', 'Integer in ipsum purus.',
			'Mauris venenatis hendrerit felis in eleifend.',
			'Praesent feugiat pellentesque leo eget pellentesque.',
			'Morbi fermentum euismod condimentum.',
			'Integer elementum convallis justo quis egestas.',
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
			'Suspendisse nec lorem iaculis erat pellentesque aliquet.',
			'Phasellus vulputate, lectus sed placerat pretium, mi purus pretium eros, et adipiscing leo erat vitae nisi.',
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
			'Proin enim mauris, ornare sit amet ornare ac, cursus porta nisi.',
			'Sed at egestas velit.', 'Praesent vel velit libero.',
			'Curabitur et tellus nulla, vel molestie ligula.',
			'Integer faucibus diam ut massa gravida convallis.',
			'Praesent eget neque tortor, a facilisis lorem.',
			'Vestibulum dapibus pretium posuere.',
			'Sed arcu est, imperdiet eu vestibulum in, luctus a libero.',
			'Sed venenatis turpis ut lacus accumsan faucibus quis vel nisi.',
			'Nullam cursus sollicitudin lectus, consequat volutpat dolor eleifend non.',
			'Morbi in purus id neque adipiscing fermentum mollis quis elit.',
			'Aenean facilisis odio in magna pellentesque et adipiscing est scelerisque.',
			'Pellentesque scelerisque tincidunt interdum.',
			'Cras posuere, felis non venenatis pellentesque, elit metus fringilla nibh, ut tempor lectus nulla non mauris.',
			'Aliquam sit amet tristique tortor.', 'Phasellus eget metus nunc.',
			'Nunc a ipsum a tortor aliquet sollicitudin.',
			'Proin viverra venenatis nibh sit amet feugiat.',
			'Proin sed elit eget lorem venenatis tincidunt.',
			'Integer non lectus vitae dolor dapibus aliquam non non lorem.',
			'Donec rutrum sodales consectetur.',
			'Cras mollis malesuada enim sit amet pulvinar.',
			'Nulla sed lectus ante.',
			'Nunc pretium, purus et consectetur venenatis, tortor est luctus lectus, et viverra turpis sapien sodales sem.',
			'In vitae tellus ut sapien dictum adipiscing laoreet at sapien.',
			'Donec blandit, purus tempus ultricies fermentum, ipsum nibh semper ipsum, eget congue mauris diam non eros.',
			'Aenean velit libero, iaculis at vehicula tristique, vehicula nec nunc.',
			'Vestibulum pellentesque iaculis libero, vitae molestie nunc egestas accumsan.',
			'Praesent molestie porta turpis, nec ultricies tortor eleifend sit amet.',
			'Sed in enim suscipit sem facilisis pretium id eu orci.',
			'Maecenas augue nibh, commodo vel feugiat eu, elementum at arcu.',
			'Suspendisse sit amet purus sit amet eros porta rhoncus faucibus et turpis.',
			'Sed et tellus est, vitae rutrum urna.',
			'Donec laoreet nisl in nisi adipiscing nec commodo nisl porta.',
			'Pellentesque lectus ligula, rutrum ut tristique at, gravida nec nibh.',
			'Nunc mollis accumsan eros, ac cursus augue accumsan vitae.',
			'Integer viverra vulputate nunc, fringilla dictum metus lacinia vel.',
			'Pellentesque a orci vitae mauris congue fringilla in ut urna.',
			'Ut id nibh ut lectus convallis viverra.',
			'Morbi ullamcorper, odio nec lacinia faucibus, sem odio dictum massa, ac tincidunt velit mauris quis magna.',
			'Donec eu dolor nisi.',
			'Aenean blandit ligula eu neque faucibus id convallis orci scelerisque.',
			'Phasellus ante tortor, rhoncus sed blandit vel, rhoncus sed lorem.',
			'Nam varius, dui nec elementum suscipit, enim ligula luctus leo, porta blandit diam diam et nisl.',
			'Etiam dapibus nibh in ligula accumsan vitae tempor arcu tempor.',
			'Duis et euismod neque.', 'Nulla in euismod risus.',
			'Nullam quis sapien dolor, a mattis lectus.',
			'Phasellus rhoncus lobortis diam.',
			'Fusce interdum justo sed nunc aliquet posuere.',
			'Phasellus elementum risus et neque rutrum fringilla volutpat purus porttitor.',
			'Mauris quam nisi, malesuada quis consectetur commodo, euismod non velit.',
			'Etiam lobortis ligula sodales erat euismod vitae mattis turpis molestie.',
			'Nulla facilisi.',
			'Sed felis arcu, pellentesque sit amet porta non, consectetur non magna.',
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
			'Sed sodales fringilla posuere.', 'Duis eget diam felis.',
			'Nunc at magna erat.', 'Nam tempor aliquam dui laoreet aliquam.',
			'Nullam nunc odio, sollicitudin quis eleifend id, pharetra at turpis.',
			'Etiam auctor facilisis egestas.', 'Pellentesque ac semper nisi.',
			'Nulla nec lorem arcu.', 'Donec nec leo felis.',
			'Sed placerat faucibus orci id bibendum.',
			'Ut at massa vitae erat pharetra hendrerit fringilla sit amet nisi.',
			'Nulla pulvinar dignissim viverra.',
			'Fusce tempus pellentesque augue eu tincidunt.',
			'Fusce risus sapien, tempus eu posuere sit amet, pharetra nec metus.',
			'Fusce eget nisl turpis.',
			'Vivamus placerat condimentum velit sed luctus.',
			'Sed eget ante sapien.',
			'Pellentesque turpis est, sagittis vitae ornare eget, tempus vitae sapien.',
			'Duis rutrum, lectus eget semper ultricies, ligula ipsum cursus dui, ut lacinia nibh ante eget lectus.',
			'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
			'Morbi in leo sit amet nisi porttitor dignissim.',
			'Ut in velit quis nulla tempus condimentum.',
			'Suspendisse ut metus vel ipsum iaculis tincidunt vitae eget justo.',
			'Etiam feugiat fringilla adipiscing.',
			'Praesent eget urna ullamcorper neque vehicula fringilla id nec ante.',
			'Ut egestas ipsum tellus.', 'Fusce vel nisi mauris.',
			'Nunc mattis mi nec mauris auctor sed consectetur turpis eleifend.',
			'Suspendisse eleifend dignissim eros, et vehicula erat vulputate eget.',
			'Suspendisse in est mauris, eu suscipit neque.',
			'Phasellus sed commodo nibh.',
			'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
			'Vivamus egestas blandit vehicula.', 'Nulla facilisi.',
			'Nulla sed pretium mauris.',
			'Sed vulputate sapien fermentum lacus bibendum scelerisque.',
			'Nulla id consequat augue.',
			'Cras suscipit viverra lacus, et convallis mi tempor vitae.',
			'Morbi ullamcorper est eu nibh egestas ut pharetra nisl mollis.',
			'Fusce posuere egestas urna non pulvinar.',
			'Sed ullamcorper enim id sem feugiat auctor.',
			'Nullam suscipit, enim ac egestas mollis, arcu libero fermentum orci, et pharetra nisl justo sed augue.',
			'Nam feugiat lacus faucibus magna pretium id mollis turpis ullamcorper.',
			'Aliquam eget leo mauris.',
			'Aliquam lobortis sem sit amet augue tincidunt auctor.',
			'Vestibulum et tellus nisl.',
			'Morbi ut lacus mauris, quis consequat enim.',
			'Aliquam neque felis, accumsan sit amet sagittis ac, molestie quis augue.',
			'Aliquam erat volutpat.', 'Nulla eu lorem ante, non sollicitudin sem.',
			'Quisque et risus sed lorem dignissim sollicitudin.',
			'Suspendisse scelerisque lobortis leo, et consectetur augue tristique eget.',
			'Fusce nec ipsum eros, et convallis lectus.',
			'Ut volutpat malesuada leo, eu porttitor dolor condimentum sollicitudin.',
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
			'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
			'Sed eu aliquam est.', 'Etiam blandit egestas augue ut blandit.',
			'Vivamus in neque erat, ac vulputate ante.',
			'Nunc accumsan tellus a ligula semper adipiscing.',
			'Quisque arcu velit, vulputate in bibendum nec, ultrices ut quam.',
			'Aenean eget pellentesque enim.',
			'Aenean vel nisi et diam placerat molestie nec sed mauris.',
			'Aliquam lobortis metus at ligula mattis vehicula.',
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
			'Quisque auctor vulputate erat nec ultrices.',
			'Donec fermentum sollicitudin massa, eget posuere leo vulputate et.',
			'Donec ac mauris enim, id hendrerit purus.',
			'Integer ut fermentum nisl.',
			'Mauris malesuada condimentum vestibulum.',
			'Phasellus adipiscing commodo dui vel tempor.', 'Suspendisse potenti.',
			'Sed pulvinar feugiat laoreet.',
			'Pellentesque tincidunt metus nec nunc varius sollicitudin nec quis felis.',
			'Maecenas a metus nisi, sit amet dapibus lectus.',
			'Aliquam quis bibendum risus.',
			'Curabitur bibendum, lorem quis malesuada aliquam, tellus ante iaculis erat, pretium rhoncus diam sem non magna.',
			'Quisque rhoncus orci et tortor faucibus interdum.',
			'Suspendisse iaculis odio et arcu dictum ut facilisis neque imperdiet.',
			'Aliquam lobortis velit ligula, id lobortis justo.',
			'Maecenas id leo id justo posuere auctor eget ac nibh.',
			'Phasellus laoreet sagittis neque non varius.',
			'Sed pretium semper diam et rhoncus.',
			'Praesent id tellus sed risus interdum pulvinar in ut nisi.',
			'Donec pulvinar dolor ac nisi ornare ullamcorper.',
			'Sed mollis nisi sed ligula pulvinar consequat.',
			'Praesent ac ligula nunc, eu convallis ante.',
			'Sed eu lacus sit amet metus mollis egestas vulputate a lorem.',
			'Sed malesuada felis eget augue congue dapibus.',
			'Vivamus posuere purus non nisi blandit ac egestas nibh vestibulum.',
			'Aenean purus velit, iaculis quis mattis gravida, imperdiet vel nulla.',
			'Ut ac ipsum neque.',
			'Nullam sem orci, lobortis vitae pulvinar a, tempus at quam.',
			'Suspendisse at enim vel justo tempus cursus eget nec quam.',
			'Curabitur ac nisi neque, sed laoreet nulla.',
			'Donec sagittis lorem in nunc rutrum adipiscing.',
			'Donec at mauris metus, tincidunt tempor quam.',
			'Sed arcu quam, suscipit ut vestibulum vel, malesuada ut lorem.',
			'Curabitur nec nibh vitae lacus aliquet convallis in id ipsum.',
			'Nullam faucibus diam quis leo laoreet vel dictum lorem pharetra.',
			'Praesent nibh neque, bibendum at scelerisque at, tempor vitae mi.',
			'Integer rutrum congue dictum.', 'Nullam tempus sagittis molestie.',
			'Nullam eu nisi ornare urna condimentum commodo ac ut nisl.',
			'Vestibulum vulputate tincidunt arcu sit amet dignissim.',
			'Maecenas condimentum ipsum vel massa placerat eget facilisis dolor venenatis.',
			'Ut ut mi eros.', 'Proin a mattis nisl.',
			'Suspendisse eu lorem in nisl rutrum porta eget at magna.',
			'Ut nulla enim, vehicula eu pharetra at, eleifend et ipsum.',
			'Vestibulum vehicula aliquam sapien, vel sodales orci scelerisque sed.',
			'Vivamus quis ipsum justo, sagittis pretium diam.',
			'Sed placerat, nisi eget fringilla sagittis, ante ipsum aliquet arcu, eu tristique tortor ante sit amet mauris.',
			'Pellentesque malesuada accumsan hendrerit.',
			'Curabitur nisl nisl, pulvinar at feugiat elementum, sagittis vel orci.',
			'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
			'Praesent convallis, sem at hendrerit tempor, urna velit tristique velit, eget laoreet neque velit eget libero.',
			'Ut tristique nisi ac erat hendrerit et gravida eros elementum.',
			'In sapien nulla, euismod feugiat aliquam quis, venenatis nec velit.',
			'Ut eu arcu vitae massa vulputate laoreet.',
			'Nulla pharetra laoreet lacus, eu ornare nisl pharetra non.',
			'Nulla euismod convallis est eu dignissim.',
			'Pellentesque pharetra, nisl eget fringilla consectetur, mauris lacus ultrices est, nec congue felis massa eu sapien.',
			'Praesent erat quam, tristique tincidunt vulputate vel, pharetra a eros.',
			'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
			'Quisque luctus blandit blandit.', 'Maecenas et vehicula nisl.',
			'Pellentesque sed consequat velit.',
			'Sed ullamcorper velit vitae nibh porta porta.',
			'Praesent nec dui ut nisi adipiscing gravida.',
			'Maecenas orci magna, placerat vitae vulputate ut, mattis nec arcu.',
			'Nunc mi nisl, auctor ac tristique vitae, porta in nunc.',
			'Donec justo elit, molestie eu tincidunt vitae, gravida ac ipsum.',
			'Suspendisse lacinia enim quis ipsum imperdiet vitae vulputate enim lobortis.',
			'Maecenas interdum nisl sed ligula convallis lobortis.',
			'Sed condimentum gravida nunc id sagittis.', 'Aenean id risus elit.',
			'Quisque sit amet risus purus.', 'Donec eu arcu velit.',
			'Duis a orci libero, sit amet cursus risus.',
			'Pellentesque aliquet, sapien ut imperdiet ultricies, dui nunc ultricies ligula, porta fringilla odio ligula eget quam.',
			'Fusce condimentum congue neque commodo hendrerit.',
			'Ut pharetra turpis mauris.',
			'Aenean aliquet, est at vehicula commodo, erat purus mollis est, nec sagittis turpis nulla ac dolor.',
			'Integer ante risus, euismod quis pulvinar sed, elementum vel arcu.',
			'Morbi quis ligula vitae felis convallis ornare in ut dui.',
			'Donec rutrum consequat eros a iaculis.',
			'Aenean turpis ligula, elementum et scelerisque sed, mattis ullamcorper dui.',
			'Vestibulum vitae magna in mauris ullamcorper facilisis ac vitae sapien.',
			'Sed non purus neque, eget facilisis nisi.',
			'Nullam consequat lorem ac urna mollis vehicula.',
			'Morbi mollis, neque nec pharetra pellentesque, odio sapien iaculis nisi, eget lacinia sem ante eu orci.',
			'Nulla varius, ligula ut eleifend hendrerit, eros nulla semper diam, nec iaculis sem turpis scelerisque nisl.',
			'Nulla id laoreet quam.',
			'Mauris metus tortor, tristique eu vulputate et, scelerisque ac justo.',
			'Nullam nisl quam, pharetra et adipiscing vel, fermentum sit amet urna.',
			'Aenean imperdiet molestie lobortis.',
			'Phasellus justo elit, tincidunt in tristique quis, placerat at eros.',
			'Fusce eget orci eget elit feugiat tincidunt.',
			'Suspendisse eget nunc in elit bibendum aliquam et viverra felis.',
			'Integer ultricies auctor ultrices.',
			'Nullam suscipit lobortis nisi, sit amet sagittis tellus tempus vestibulum.',
			'Fusce non ante neque, eget accumsan mi.',
			'In in arcu vel metus condimentum fermentum et nec nisl.',
			'Nunc sed libero nec lorem consectetur egestas sed vel nisi.',
			'Suspendisse in lectus at libero aliquam hendrerit quis sed ante.',
			'Aenean id odio ut tellus sollicitudin lacinia.',
			'Suspendisse vel dapibus risus.',
			'Ut vulputate augue vitae leo scelerisque a iaculis dui sagittis.',
			'Etiam quis justo est, eget convallis metus.', 'Cras non sem risus.',
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
			'Vestibulum lectus ante, porttitor ultricies scelerisque quis, iaculis id elit.',
			'Integer at erat tortor.',
			'Nullam in libero metus, ac pulvinar mauris.',
			'Praesent tincidunt lobortis mi, nec mollis est adipiscing eu.',
			'Etiam sodales fringilla lorem et aliquet.',
			'Pellentesque odio magna, pharetra eget adipiscing non, interdum sit amet nisl.',
			'Sed quis egestas orci.',
			'Phasellus sit amet urna vitae ante ultricies dignissim.',
			'Pellentesque feugiat tempus sagittis.',
			'Pellentesque vel venenatis lectus.',
			'Sed at augue quis nulla feugiat hendrerit.',
			'Suspendisse justo enim, varius a mollis ac, tristique a sem.',
			'Integer sed libero at nibh mollis posuere non ac mi.',
			'Nullam ac risus purus.', 'Duis sed suscipit augue.',
			'Phasellus ante lacus, porta sollicitudin adipiscing vel, blandit et eros.',
			'Phasellus tortor ante, ullamcorper feugiat ultricies et, pretium non eros.',
			'In vel velit eu elit hendrerit facilisis ut vitae nisi.',
			'Vivamus tortor nibh, molestie sit amet semper vitae, convallis vitae ligula.',
			'Sed ultrices, ante eget porttitor consequat, magna arcu molestie nulla, ac volutpat enim massa posuere urna.',
			'Nulla facilisi.', 'Mauris congue euismod augue ac fringilla.',
			'Ut justo elit, iaculis quis molestie in, iaculis eu massa.',
			'Nunc ipsum ipsum, mattis in porta sed, adipiscing eget sapien.',
			'Proin quis mi nulla, eu fermentum mi.',
			'Maecenas odio nunc, scelerisque at viverra sit amet, bibendum sit amet nulla.',
			'Nunc sit amet tortor non risus gravida aliquet.',
			'Ut in diam et nisi dictum vehicula id consectetur dolor.',
			'Morbi vestibulum ultricies ornare.',
			'Ut non nunc elit, quis aliquet nunc.',
			'Vivamus augue turpis, aliquet ac elementum eget, fringilla ut odio.',
			'Praesent accumsan nunc sit amet sapien laoreet id tempor erat pretium.',
			'Maecenas posuere aliquet ligula, sit amet aliquam massa rutrum eu.',
			'Vestibulum at ipsum odio.', 'Donec non nunc enim, in tempor lorem.',
			'Cras tempor viverra erat eget feugiat.',
			'Phasellus lorem sapien, iaculis eget interdum at, tincidunt vitae nibh.',
			'Etiam eu adipiscing mi.',
			'Integer ut justo a ligula suscipit malesuada.',
			'Quisque felis elit, tempor vitae porta sit amet, condimentum vitae massa.',
			'Proin id tortor sit amet tellus adipiscing ornare id eu lacus.',
			'In pretium justo ut dui cursus in convallis tortor aliquam.',
			'Curabitur vel urna erat, ut luctus neque.',
			'Nulla viverra, nibh a luctus pellentesque, leo lorem varius orci, ut posuere leo ligula a dolor.',
			'Etiam a ante sed neque ultrices vehicula.',
			'Phasellus ut augue metus, vel hendrerit felis.',
			'Curabitur a enim non sem rhoncus lobortis.',
			'Mauris ultricies placerat sagittis.',
			'Donec vestibulum ligula a velit vehicula blandit lacinia lorem pretium.',
			'Praesent imperdiet dui vitae dui lacinia sit amet ultrices erat ultrices.',
			'Vivamus sodales ullamcorper quam, ac interdum metus gravida et.',
			'Aliquam augue velit, rutrum id consectetur nec, pharetra at ante.',
			'Praesent vestibulum scelerisque odio eget luctus.',
			'Cras nisl dolor, dapibus id lacinia at, auctor sed felis.',
			'Phasellus ut turpis neque, sit amet tincidunt nisi.',
			'Proin augue mauris, volutpat at porttitor commodo, egestas in erat.',
			'Mauris leo lacus, pellentesque vitae fermentum pretium, malesuada eget augue.',
			'Sed cursus tellus vel lorem auctor a aliquam augue hendrerit.',
			'Aliquam erat volutpat.', 'Donec feugiat mollis nunc in cursus.',
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
			'Nullam tristique turpis a sem euismod in tincidunt est elementum.',
			'Maecenas luctus sem vel justo consectetur nec lacinia neque tincidunt.',
			'Sed iaculis sagittis lacus, sed porta tortor faucibus a.',
			'Maecenas nec tortor pulvinar turpis gravida ultricies ut non odio.',
			'Sed facilisis, augue vel dapibus luctus, libero felis commodo lacus, a ultricies mi est at nulla.',
			'In hac habitasse platea dictumst.',
			'Curabitur sit amet enim dui, ac bibendum odio.',
			'Praesent molestie aliquet elit vel vulputate.',
			'Aenean sodales eleifend velit, sit amet imperdiet ligula cursus sit amet.',
			'Nullam quis velit varius libero lobortis malesuada.',
			'Curabitur pharetra nisl quis dui posuere pretium.',
			'Fusce tellus libero, iaculis eu varius nec, auctor et est.',
			'Duis semper libero ac risus sollicitudin gravida.',
			'Sed molestie tortor quis libero ultrices eu tempor elit eleifend.',
			'Vestibulum pretium, velit at pharetra egestas, urna leo dapibus risus, ut pulvinar turpis mi ultrices eros.',
			'Duis rhoncus cursus feugiat.',
			'Duis dolor nunc, viverra in pellentesque at, consectetur quis neque.',
			'Praesent tincidunt justo in quam tempus sagittis.',
			'Nullam eu mattis sem.', 'In posuere vulputate interdum.',
			'Nunc bibendum ipsum in orci rutrum ultrices.',
			'Vestibulum posuere nisi a dui ultricies placerat.',
			'Praesent elementum tellus vel magna eleifend in imperdiet ipsum bibendum.',
			'Donec varius nisi quis nisl ultrices fringilla.',
			'Suspendisse molestie euismod vehicula.', 'Quisque ut ligula dui.',
			'Sed luctus ullamcorper augue at gravida.',
			'Duis commodo posuere nibh, eget suscipit purus imperdiet interdum.',
			'Duis vitae dui id lectus molestie aliquam.',
			'Etiam elementum, ipsum non dapibus congue, tellus lorem ultrices quam, convallis dictum dolor justo a orci.',
			'Nunc egestas quam et nisl ultrices eu pellentesque erat dictum.',
			'Suspendisse potenti.', 'Nulla facilisi.', 'Donec eu nunc arcu.',
			'Nullam et lectus enim, ut aliquet lectus.', 'Morbi sit amet mi dolor.',
			'Aliquam magna enim, pellentesque quis fermentum a, dictum ac augue.',
			'Suspendisse nisl est, elementum eu ultricies id, euismod consectetur arcu.',
			'Aenean nec velit eros.',
			'Etiam mollis dolor vitae magna egestas sollicitudin.',
			'Fusce hendrerit, ligula sit amet consequat sodales, magna leo pellentesque ante, et venenatis tellus justo nec ipsum.',
			'Mauris ornare vestibulum ipsum id interdum.',
			'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
			'Nulla id lacus urna.',
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
			'Vivamus hendrerit risus et mauris condimentum ac tincidunt leo euismod.',
			'Vestibulum fermentum convallis est sit amet dictum.',
			'Suspendisse ultrices, dolor dictum laoreet euismod, dui orci hendrerit justo, et suscipit mi sem ut lectus.',
			'Integer imperdiet metus sit amet purus molestie sed dignissim turpis placerat.',
			'Donec semper purus vitae velit pretium consequat suscipit nisi lobortis.',
			'Nunc egestas aliquet felis, in dapibus nunc lobortis at.',
			'Integer est elit, commodo et porttitor posuere, pellentesque quis sem.',
			'Nam vitae justo sit amet mi luctus tincidunt.',
			'Nam pulvinar elementum arcu, at consequat nisl consequat in.',
			'Vivamus in mi ornare dui egestas egestas.',
			'Mauris consequat accumsan mi, at euismod velit pulvinar convallis.',
			'Ut aliquam faucibus urna, interdum fringilla lorem pellentesque eu.',
			'Duis eget nunc orci.',
			'Integer vitae dolor sed metus feugiat tempor id non ipsum.',
			'Proin gravida nisl ac orci fermentum adipiscing.',
			'Vivamus vitae bibendum enim.', 'Nullam quis molestie enim.',
			'Proin non arcu nunc, vitae consectetur justo.',
			'Integer risus purus, sollicitudin ut lobortis vel, pretium et tortor.',
			'Pellentesque quis sapien in justo dapibus tincidunt id sed felis.',
			'Etiam ullamcorper tincidunt odio, vehicula commodo augue porttitor ut.',
			'Ut at lectus mauris, ac tincidunt massa.',
			'Praesent ut felis leo, et luctus nisl.',
			'In felis tortor, luctus sed varius in, commodo at tellus.',
			'Mauris in molestie ligula.',
			'Duis cursus tincidunt metus sed imperdiet.',
			'Quisque fermentum, nibh a tristique venenatis, lacus felis porttitor sapien, et egestas augue nisl a augue.',
			'Aliquam non ante velit, non aliquam mauris.',
			'Mauris imperdiet tellus quis felis faucibus vitae volutpat magna convallis.',
			'Phasellus tincidunt justo et purus mollis vitae aliquam nisi consequat.',
			'Ut et nisl eget urna consequat varius at in mi.',
			'Curabitur quis leo ut felis ullamcorper eleifend at ut tortor.',
			'Suspendisse viverra orci at odio blandit aliquam.',
			'Suspendisse pharetra luctus magna a rutrum.',
			'Nullam interdum adipiscing consectetur.',
			'Donec a elit condimentum elit mattis gravida.',
			'Duis lacinia aliquet nulla.',
			'Pellentesque viverra posuere purus, non feugiat nulla dictum sed.',
			'Suspendisse pharetra dolor id libero facilisis euismod.',
			'Mauris nec vestibulum purus.',
			'Pellentesque aliquet, justo pharetra semper commodo, mauris eros laoreet est, sit amet rhoncus dui velit vitae libero.',
			'Fusce eu turpis magna, sed pharetra metus.',
			'Integer ut consectetur lacus.',
			'Phasellus iaculis sapien in diam rhoncus quis interdum enim consequat.',
			'Cras arcu nisl, aliquam eu viverra eget, congue sit amet ligula.',
			'Integer pulvinar, lectus ut aliquam tristique, mi tortor commodo odio, non posuere enim orci malesuada odio.',
			'Nulla vehicula imperdiet quam, vel sollicitudin neque imperdiet id.',
			'Nunc nec varius quam.', 'Aenean placerat mattis purus eget vehicula.',
			'In eget metus quis lacus volutpat dictum.',
			'Curabitur lorem magna, porttitor accumsan fermentum at, laoreet eu justo.',
			'Nam non nisl volutpat felis imperdiet porta.',
			'Curabitur ac sem lacus, vitae dignissim metus.',
			'Aenean tincidunt iaculis varius.',
			'Integer sagittis elementum condimentum.',
			'Duis nisi justo, vestibulum et egestas vel, aliquam at nibh.',
			'Sed nisl elit, hendrerit sed elementum quis, molestie ac nulla.',
			'Maecenas ipsum sem, pharetra et facilisis nec, tincidunt vitae ipsum.',
			'Suspendisse interdum, diam ac congue congue, massa odio eleifend nibh, dignissim rhoncus eros risus at quam.',
			'Suspendisse pretium bibendum nulla eget ullamcorper.',
			'Curabitur at justo erat.', 'Ut et ligula lectus, et tincidunt erat.',
			'Fusce consectetur auctor nibh id euismod.',
			'Sed ultrices pulvinar nisi, sed gravida leo rutrum non.',
			'Donec libero nunc, porttitor a rhoncus eget, consectetur quis urna.',
			'Quisque semper felis sit amet tortor feugiat a laoreet magna scelerisque.',
			'Donec nec euismod nunc.',
			'Aenean ut ipsum nunc, porttitor mollis ante.',
			'Aenean eget est urna.', 'Nulla sed nulla quis augue dictum eleifend.',
			'Cras pharetra felis vel lorem condimentum aliquam.',
			'Morbi convallis tincidunt ligula, ut auctor velit luctus nec.',
			'Nulla facilisi.',
			'Quisque tempus ante in arcu sollicitudin eu tempor nulla ornare.',
			'Nam nec turpis ligula.', 'Sed eget augue tortor.',
			'Aenean aliquam pellentesque placerat.',
			'Quisque imperdiet neque eget lectus rhoncus eu elementum nunc placerat.',
			'Vestibulum non tortor facilisis justo pretium congue.',
			'Cras varius interdum sagittis.',
			'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris a quam quis augue pulvinar egestas ut non erat.',
			'Donec at augue quam, vitae lobortis justo.',
			'Nulla euismod, justo vitae porttitor luctus, ipsum dui condimentum turpis, id facilisis eros lorem in urna.',
			'Donec hendrerit dolor a purus laoreet consectetur.',
			'Vestibulum sed erat quis nisi molestie placerat in sit amet justo.',
			'Aliquam id lorem erat.', 'Vivamus eget nisl ipsum.',
			'Sed sodales dolor sit amet nisl rutrum vestibulum.',
			'Maecenas egestas accumsan diam eu suscipit.',
			'Sed faucibus erat a mi ullamcorper porttitor.',
			'Nulla posuere, lectus vitae tincidunt pharetra, mi lectus aliquet lectus, a ultrices velit turpis vitae magna.',
			'Nunc tellus mauris, adipiscing at ornare ac, posuere vitae quam.',
			'Nulla facilisi.', 'Nulla pellentesque pellentesque elementum.',
			'Aliquam vulputate ultricies tincidunt.',
			'Nam vulputate mollis porttitor.',
			'Nam gravida leo mauris, non imperdiet metus.',
			'Praesent sagittis molestie sagittis.',
			'Aliquam purus dui, vestibulum sit amet faucibus ut, euismod ut urna.',
			'Duis blandit purus et odio malesuada ornare.',
			'In vehicula varius sem, vel condimentum sem blandit vel.',
			'Sed dignissim tortor nec urna tincidunt egestas nec nec eros.',
			'Vestibulum cursus, tellus a consequat rhoncus, eros nulla vestibulum magna, malesuada tempor magna mauris sit amet sapien.',
			'Praesent at ante mi.',
			'Etiam pretium felis accumsan dui faucibus eu gravida metus eleifend.',
			'Integer ultricies, velit quis dictum fringilla, est lorem aliquam urna, et volutpat magna risus in dolor.',
			'Donec nisl erat, gravida porta gravida sed, egestas nec risus.',
			'In hac habitasse platea dictumst.',
			'Curabitur tempus, metus fringilla adipiscing mollis, neque velit aliquet sapien, in facilisis velit felis quis mi.',
			'Nunc odio urna, aliquam mattis blandit a, varius eget tellus.',
			'Sed in nulla nec nulla sagittis interdum.',
			'Suspendisse nec velit at purus consectetur elementum eget et odio.',
			'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum varius pretium tellus in varius.',
			'Quisque tellus augue, viverra quis pretium ut, blandit nec ligula.',
			'Maecenas feugiat elementum convallis.',
			'Phasellus tristique erat ac mi tristique euismod.',
			'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
			'Donec neque urna, vulputate at consequat eget, malesuada eget ipsum.',
			'Aliquam erat volutpat.', 'Sed id eleifend tellus.',
			'Curabitur et nisi neque.', 'Proin ut odio orci, quis venenatis nulla.',
			'Aenean lacinia tincidunt purus et pellentesque.',
			'Donec ac lacus mi, nec pellentesque tortor.',
			'Mauris tempus scelerisque tellus eu rutrum.',
			'Duis lacinia congue vehicula.',
			'Nunc in est in magna varius aliquam eget at felis.',
			'Curabitur eget orci diam, id molestie orci.',
			'Mauris malesuada blandit posuere.',
			'Pellentesque molestie diam id turpis ornare non dapibus tellus blandit.',
			'Praesent accumsan interdum porttitor.', 'Ut feugiat rutrum euismod.',
			'Suspendisse et nunc lectus.',
			'Donec vulputate mi vitae nulla tempor non pulvinar nisi eleifend.',
			'Morbi bibendum nisi sed diam aliquam laoreet.',
			'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec porttitor bibendum odio, id elementum erat eleifend nec.',
			'Quisque fringilla feugiat dictum.',
			'Aenean justo magna, elementum eget rutrum et, dapibus et eros.',
			'Pellentesque sit amet turpis vitae leo viverra eleifend.',
			'Cras quis odio lorem.', 'Maecenas a tellus dolor.',
			'In vehicula auctor metus, rhoncus eleifend nisi condimentum sit amet.',
			'Aliquam erat volutpat.', 'Nulla sed massa nisl, id aliquam felis.',
			'Proin tempor tincidunt hendrerit.',
			'Proin et sem nisl, eu viverra mauris.',
			'Integer suscipit tortor sed massa tincidunt euismod.',
			'Etiam arcu enim, accumsan tincidunt lobortis id, tristique vel mi.',
			'Pellentesque laoreet mauris sit amet nunc egestas ac tincidunt ipsum egestas.',
			'Nam dui magna, luctus non tempus et, ullamcorper quis ligula.',
			'Curabitur urna tortor, interdum quis molestie ut, eleifend interdum eros.',
			'Donec leo sem, condimentum sed tincidunt ac, blandit vel lacus.',
			'Nam ut metus quam.', 'Duis a accumsan augue.',
			'Maecenas tincidunt nisi at neque euismod eu vestibulum odio vestibulum.',
			'Maecenas quis dictum libero.',
			'Integer vel dui bibendum mauris aliquam viverra.',
			'Maecenas urna nulla, dignissim a placerat quis, pharetra ac quam.',
			'Aenean eu imperdiet justo.', 'Vestibulum eu fringilla massa.',
			'Nam consectetur ante et ipsum semper quis sagittis magna pharetra.',
			'Cras eu nisi in libero venenatis condimentum.',
			'Maecenas semper ultrices sem, ac luctus nisi gravida et.',
			'Aliquam erat volutpat.',
			'Nulla facilisis vestibulum risus, non consequat massa adipiscing non.',
			'Duis tincidunt, nisi sed porttitor pellentesque, sapien nunc malesuada velit, ac rutrum mi sapien a ipsum.',
			'Ut et odio ante, in pellentesque quam.', 'Duis id augue diam.',
			'Aliquam pulvinar arcu at risus dignissim vestibulum.',
			'Vivamus vulputate justo eget velit cursus rhoncus.',
			'Morbi scelerisque volutpat posuere.',
			'Aliquam aliquet lobortis lacus ut viverra.',
			'Duis sed enim quis ante elementum semper.',
			'Donec mauris mauris, tincidunt vel fermentum sodales, mattis eget arcu.',
			'Aliquam erat volutpat.',
			'Nullam varius, eros non vehicula sagittis, est sem vehicula quam, sit amet faucibus orci mi non urna.',
			'Etiam eget elit erat.',
			'Sed dapibus ipsum sit amet nunc facilisis et tincidunt augue iaculis.',
			'Suspendisse est orci, ultricies ut bibendum nec, laoreet mollis nunc.',
			'Donec elementum feugiat aliquet.',
			'Duis vestibulum sem id odio ullamcorper convallis.',
			'Nam non augue sed mauris malesuada interdum a id leo.',
			'Proin pretium viverra libero et mollis.',
			'Maecenas et nisl a elit ullamcorper dapibus at sed enim.',
			'Aliquam risus dui, egestas eget consequat nec, ultrices quis turpis.',
			'Aliquam sollicitudin odio dui, sed ullamcorper mauris.',
			'Maecenas tortor nisi, suscipit vitae hendrerit vitae, vestibulum quis mi.',
			'Vestibulum sit amet lorem sapien.',
			'Donec nec augue in odio bibendum tempus.', 'Mauris suscipit urna dui.',
			'Curabitur venenatis lacinia sollicitudin.', 'Nunc vel tortor erat.',
			'Curabitur interdum rutrum condimentum.', 'Suspendisse potenti.',
			'Sed vel enim mauris, ornare ullamcorper eros.',
			'Nulla tempor, ante vitae venenatis malesuada, orci nisi volutpat nibh, in cursus nisl neque et augue.',
			'Praesent ultrices urna egestas magna porttitor adipiscing.',
			'Mauris porta tincidunt porttitor.',
			'Proin vehicula, erat nec posuere venenatis, risus purus suscipit elit, at auctor nibh neque ac odio.',
			'Proin tincidunt consequat velit, et posuere magna consequat non.',
			'In sed lectus elit, et condimentum magna.',
			'Nulla sed nisi quis nisl faucibus varius sed nec elit.',
			'Cras dignissim libero purus.',
			'Morbi elementum risus non nulla ultrices ut tempor lectus molestie.',
			'Nulla ac nisl eros, sed suscipit felis.',
			'Pellentesque cursus tincidunt augue ut venenatis.',
			'Sed in justo nec quam scelerisque tincidunt id at arcu.',
			'Aenean ligula nunc, interdum eu vehicula et, scelerisque sit amet purus.',
			'Sed suscipit, sem id pretium pharetra, nunc risus eleifend tortor, ut tincidunt nisi mauris vel mauris.',
			'Nam facilisis porttitor tortor eget laoreet.',
			'Quisque dapibus commodo neque tempus semper.',
			'Praesent bibendum pretium vulputate.',
			'Proin posuere convallis molestie.',
			'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer porta odio non nunc scelerisque vel sollicitudin neque commodo.',
			'Nulla quis placerat magna.',
			'Vivamus sodales dui id erat euismod a convallis enim suscipit.',
			'Nulla quis sem in tellus eleifend vulputate in at massa.',
			'Donec convallis, ligula ac viverra interdum, justo ante faucibus ligula, at convallis elit lacus sed erat.',
			'Suspendisse eget tortor lorem, nec ultricies tortor.',
			'Maecenas vel mauris nisl, id malesuada nisl.',
			'Sed mattis fringilla gravida.',
			'Mauris mauris urna, volutpat in luctus ac, aliquet sit amet quam.',
			'Etiam leo nisi, iaculis at dapibus ac, mollis ut dui.',
			'Curabitur ultricies, tellus nec feugiat feugiat, magna nulla adipiscing enim, id iaculis lacus ligula vel velit.',
			'Pellentesque id lectus enim, nec consequat est.',
			'Quisque pretium metus quis ipsum dignissim convallis a aliquam diam.',
			'Suspendisse potenti.', 'In vel mauris sem, a venenatis magna.',
			'Duis sed justo in nulla ornare tincidunt.',
			'Vestibulum at velit ligula, in fringilla urna.',
			'Duis eu suscipit nibh.',
			'Praesent quam lorem, pretium eget viverra id, feugiat elementum neque.',
			'Donec magna erat, dictum sed tincidunt vitae, gravida ut erat.',
			'Vivamus a elit nisl, ac lobortis massa.',
			'Quisque hendrerit egestas lorem, eget eleifend ipsum vulputate quis.',
			'Morbi volutpat justo eget tortor hendrerit quis rutrum tellus viverra.',
			'Maecenas volutpat odio ac magna malesuada hendrerit vulputate erat tristique.',
			'Vivamus fringilla, felis a malesuada euismod, quam nulla lacinia ante, sed suscipit mauris nulla eu nulla.',
			'Duis non luctus velit.', 'Sed et lorem ut eros adipiscing imperdiet.',
			'Morbi risus felis, tincidunt vitae semper ut, adipiscing ac odio.',
			'Suspendisse ac mollis risus.',
			'Pellentesque id leo nec risus porta tincidunt.',
			'Pellentesque at luctus orci.',
			'Morbi urna metus, semper quis sagittis id, accumsan quis sapien.',
			'Etiam ipsum eros, faucibus ut molestie in, lobortis sed odio.',
			'Ut adipiscing laoreet turpis, ac dapibus augue adipiscing et.',
			'Vivamus eu est sed ipsum iaculis cursus.',
			'Praesent magna libero, venenatis nec adipiscing nec, dictum quis mi.',
			'Mauris tempor condimentum dui et vulputate.',
			'Donec venenatis ullamcorper felis, non gravida sem sodales vitae.',
			'Vivamus purus dui, porttitor a rutrum ac, condimentum vitae est.',
			'Vivamus ut purus at ipsum luctus feugiat vitae in ligula.',
			'Donec pretium dapibus orci, quis semper magna facilisis non.',
			'Nam laoreet felis non ipsum euismod quis ullamcorper nisl consequat.',
			'Sed consectetur suscipit tortor, id mattis dui malesuada non.',
			'Nunc id eros rhoncus ipsum scelerisque commodo in et nisi.',
			'Vestibulum imperdiet lorem vel nisi consequat sed egestas quam mollis.',
			'Donec volutpat semper purus, eget pharetra felis cursus sed.',
			'Sed lacinia commodo turpis id accumsan.',
			'Proin venenatis, orci at mattis euismod, eros lectus pellentesque ipsum, quis accumsan nunc tortor et mi.',
			'Aliquam erat volutpat.', 'Nunc non orci ante.',
			'Sed auctor pharetra lectus, at dictum ipsum tempor vitae.',
			'Proin a sodales felis.',
			'Nunc feugiat ante massa, vel porttitor nisl.',
			'Aenean malesuada bibendum elit in fermentum.',
			'Vestibulum aliquet egestas velit, et congue felis scelerisque at.',
			'Suspendisse ligula lacus, viverra hendrerit condimentum quis, adipiscing eu massa.',
			'Fusce sollicitudin porta nulla id ullamcorper.',
			'Maecenas lacinia lacus ac augue elementum luctus.',
			'Vestibulum nunc lacus, molestie eu fermentum sed, aliquam cursus elit.',
			'Maecenas odio lectus, dapibus malesuada lobortis a, ultricies et metus.',
			'Duis sit amet tellus risus.', 'In volutpat lobortis placerat.',
			'Donec ac ante id orci congue placerat.',
			'Nunc nec felis non ipsum venenatis bibendum sed sed nisl.',
			'Quisque facilisis justo in nunc convallis vel sagittis urna eleifend.',
			'Curabitur non adipiscing enim.',
			'Cras non risus id tellus mollis dictum.',
			'Donec facilisis velit sit amet erat vulputate accumsan.',
			'Quisque luctus, augue consequat condimentum hendrerit, libero mauris ultrices diam, eu blandit sapien purus sed turpis.',
			'Vestibulum ut mi eu orci imperdiet tincidunt eu sit amet nulla.',
			'Aliquam rutrum lacus at massa posuere vel euismod ligula dignissim.',
			'Aenean egestas enim dapibus tortor tincidunt elementum.',
			'Nulla facilisi.',
			'Phasellus sed nisl sit amet turpis posuere rhoncus.',
			'Aenean odio nunc, ultricies accumsan vulputate a, sagittis id lorem.',
			'Aliquam commodo velit vel tortor tristique tincidunt sollicitudin sapien pretium.',
			'Suspendisse sed risus vel quam sodales egestas.',
			'In tincidunt vestibulum augue, nec porttitor diam consectetur ac.',
			'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
			'Vivamus pellentesque ultricies purus, at faucibus urna posuere non.',
			'Suspendisse consequat velit consequat ligula rhoncus eu condimentum sapien posuere.',
			'Duis sit amet ligula nec erat vestibulum lacinia vitae et magna.',
			'Aliquam adipiscing adipiscing urna dapibus rutrum.',
			'Praesent ac velit eu urna adipiscing mattis ac ut tellus.',
			'Aliquam erat volutpat.',
			'Etiam sapien ipsum, interdum a dignissim ac, laoreet eu erat.',
			'Aenean eu tellus quis elit viverra interdum.',
			'Donec egestas nisi a lorem pretium mollis.',
			'Sed est ipsum, auctor id tempor sed, rutrum ut eros.',
			'Quisque posuere enim at enim ultricies vehicula.',
			'Praesent et nunc id sapien tincidunt facilisis.',
			'Nullam vehicula porttitor viverra.', 'Nullam vel dictum nisi.',
			'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
			'Praesent faucibus tempus justo, quis vulputate massa hendrerit vitae.',
			'Integer consectetur sollicitudin euismod.',
			'Sed aliquet accumsan auctor.',
			'Praesent interdum mattis tellus a aliquet.',
			'Nullam eget eros a nisl eleifend aliquet sed ac nisi.',
			'Fusce mattis orci quis purus tincidunt auctor.',
			'Integer non metus convallis nunc scelerisque ultricies eget a enim.',
			'Donec viverra arcu non sapien vestibulum pharetra.',
			'Curabitur et nulla at neque luctus pellentesque ut ac ligula.',
			'Pellentesque tellus nisi, venenatis id rhoncus id, sagittis a ante.',
			'Morbi pulvinar consequat bibendum.',
			'Suspendisse dictum, augue non tincidunt consectetur, nibh neque viverra risus, id lobortis tellus felis at nulla.',
			'Fusce ac ipsum non augue varius dapibus.',
			'Nullam in libero ut dolor sollicitudin auctor in at enim.',
			'Donec nec vehicula mauris.',
			'Vestibulum pulvinar vehicula sollicitudin.',
			'Donec imperdiet interdum lectus eget vehicula.',
			'Nunc ultrices elementum lacus, eget vulputate libero mollis nec.',
			'Vivamus ac viverra turpis.',
			'Vestibulum condimentum tempus massa, sit amet euismod ipsum malesuada vel.',
			'In vulputate blandit orci, in ultrices nisl cursus in.',
			'Sed eget diam diam, ut mattis sem.',
			'Vivamus pulvinar facilisis euismod.',
			'Donec at odio non elit facilisis adipiscing eget a augue.',
			'Sed fermentum condimentum quam, a mattis sapien luctus vel.',
			'Donec nec gravida augue.',
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
			'Nullam eu quam quis est dapibus volutpat.', 'Nulla facilisi.',
			'Maecenas at nisi et tortor pretium rutrum.',
			'Nullam a metus eu est convallis placerat vel at massa.',
			'Aenean at nunc faucibus ligula laoreet pulvinar.',
			'Maecenas ante tortor, molestie eu condimentum id, varius ac metus.',
			'Vestibulum magna arcu, pellentesque sit amet facilisis id, consequat eu odio.',
			'Quisque cursus rutrum nibh.', 'Donec feugiat iaculis feugiat.',
			'Etiam augue ligula, commodo ac placerat nec, laoreet ac nisl.',
			'Fusce nec ante eros, eget condimentum odio.',
			'Integer varius fringilla mauris at convallis.',
			'Nunc ac nisi id eros laoreet porta eu vitae risus.',
			'Vivamus pulvinar dui est, et feugiat tellus.',
			'In et lorem sit amet quam egestas blandit vel vel ipsum.',
			'Nullam ultricies magna lacus.',
			'Donec vulputate, nisi vel elementum interdum, diam magna ultrices mi, vel laoreet odio nunc non diam.',
			'Vestibulum volutpat tortor eget nibh interdum laoreet.',
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
			'Mauris quis nunc mauris, dapibus pulvinar enim.',
			'Duis elementum feugiat nisi sit amet consequat.',
			'Pellentesque a quam justo.',
			'In sed felis odio, ullamcorper dapibus justo.',
			'In hac habitasse platea dictumst.',
			'Fusce eget eros in mi sollicitudin pulvinar.',
			'Curabitur dolor ligula, condimentum non hendrerit eu, ultricies id nulla.',
			'Duis nec magna non urna viverra ornare a vel leo.',
			'Etiam risus elit, consectetur eget placerat sit amet, volutpat eu nisl.',
			'Maecenas iaculis nibh sit amet sem varius aliquet.',
			'Morbi tincidunt vestibulum diam ac ultricies.',
			'Phasellus elementum malesuada lacus, commodo vehicula mi tincidunt a.',
			'Duis sed massa ligula.', 'Pellentesque a convallis sapien.',
			'Fusce pulvinar odio nec nisi consectetur ullamcorper.',
			'Maecenas non tortor libero.',
			'Quisque nisl purus, sodales eu luctus sit amet, condimentum eget lectus.',
			'Quisque aliquam placerat libero, dapibus porta dui vestibulum a.',
			'Mauris ante nisl, porta eget laoreet quis, molestie scelerisque urna.',
			'Aliquam urna leo, tempor eu volutpat nec, blandit ac est.',
			'Donec tempor dui et nulla ullamcorper semper euismod libero viverra.',
			'Pellentesque eu tortor et dolor elementum varius.',
			'Mauris mollis fermentum eros, sit amet malesuada orci ultricies dictum.',
			'Vestibulum et congue sapien.',
			'Etiam id velit vitae nisl convallis feugiat vitae sed erat.',
			'Morbi ullamcorper sollicitudin enim, id rutrum purus consequat at.',
			'Pellentesque consectetur eleifend dolor eget volutpat.',
			'In rutrum turpis nec mauris vehicula sit amet lacinia sem tristique.',
			'Aliquam erat volutpat.', 'In non elit nec nibh varius tempor.',
			'Pellentesque sit amet orci quis felis sagittis consequat.',
			'Nullam elit justo, sollicitudin eget iaculis vel, elementum vitae orci.',
			'Fusce feugiat nulla at massa tempus in dictum libero sollicitudin.',
			'Cras interdum ullamcorper tempus.',
			'Aenean nisi odio, tempor sed fermentum quis, feugiat id nisl.',
			'Sed vehicula iaculis auctor.',
			'Mauris tempor lectus vel ipsum feugiat aliquam.',
			'Proin at eros quis dolor consectetur interdum.',
			'Fusce volutpat mi eu leo lobortis vel pretium sapien egestas.',
			'In lectus arcu, eleifend ut venenatis vitae, mollis eget elit.',
			'Donec quis mi quis mauris sodales euismod.', 'Sed eget nulla lectus.',
			'Aenean turpis purus, suscipit malesuada dictum at, vestibulum nec ipsum.',
			'Phasellus eu pulvinar velit.',
			'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin eleifend congue libero a semper.',
			'Vivamus dictum massa non leo luctus bibendum.',
			'Mauris feugiat, velit non pellentesque sollicitudin, ligula nisi rhoncus mi, et convallis leo ligula tempus elit.',
			'Etiam lacinia velit ac lacus hendrerit ornare.',
			'Maecenas convallis gravida velit, at egestas ipsum commodo ac.',
			'Cras et diam libero.', 'In hac habitasse platea dictumst.',
			'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
			'Donec a urna sem.', 'Etiam quis ligula augue, eu aliquet dui.',
			'Ut neque justo, ultrices et bibendum eu, vestibulum ac dui.',
			'Quisque consequat, tortor et venenatis accumsan, libero nulla mollis justo, nec vulputate neque turpis ac erat.',
			'Praesent auctor mollis urna in eleifend.',
			'Pellentesque lacinia ipsum ut justo ultrices ullamcorper.',
			'Nunc eu pulvinar leo.', 'Integer eget nunc mi.',
			'Maecenas varius euismod ante in congue.',
			'Donec id nisi id ligula tincidunt egestas.',
			'Sed metus magna, dictum et rutrum et, fringilla et odio.',
			'Ut consectetur rhoncus eros et rhoncus.',
			'Proin pulvinar turpis nec ipsum vulputate laoreet.',
			'Phasellus egestas magna nec ante facilisis nec dapibus dui pharetra.',
			'Nulla vehicula dictum tellus et euismod.',
			'Donec nec augue sed odio mattis ultrices vitae sit amet felis.',
			'Suspendisse potenti.', 'Nullam porttitor congue est vitae suscipit.',
			'Aenean vel luctus est.',
			'Nunc suscipit justo at felis auctor vitae congue felis eleifend.',
			'Integer mauris mauris, pretium sit amet sollicitudin ut, lobortis in felis.',
			'Praesent facilisis cursus enim.',
			'Vivamus scelerisque consectetur leo, at mollis purus blandit sed.',
			'Integer aliquam molestie fringilla.',
			'Nullam pretium lobortis diam, commodo lacinia tortor posuere vitae.',
			'Donec in tempor magna.',
			'Vivamus lobortis dignissim sapien, auctor vestibulum mauris accumsan eu.',
			'Vestibulum eget est ut velit pellentesque ullamcorper lobortis ac nisl.',
			'Proin pretium eros at turpis luctus posuere quis et mauris.',
			'Ut ut dictum dolor.', 'Duis eu justo tellus, quis hendrerit mi.',
			'Cras pharetra tempor convallis.',
			'Morbi mollis luctus enim, non semper urna auctor nec.',
			'Phasellus id enim at elit consectetur molestie.',
			'Maecenas faucibus ante in nulla varius vitae fermentum lorem euismod.',
			'Quisque fringilla hendrerit molestie.',
			'Quisque posuere placerat enim.',
			'Proin at nisi odio, pretium pharetra nibh.',
			'Nullam commodo rhoncus dui dapibus tincidunt.',
			'Sed sapien mi, ultrices sit amet egestas vel, convallis vel ipsum.',
			'Integer non arcu urna, nec varius turpis.',
			'Curabitur porttitor, diam in commodo hendrerit, est purus pulvinar sapien, et tristique nulla dui eu eros.',
			'Sed convallis faucibus sapien, tincidunt suscipit ante dignissim quis.',
			'Aliquam id mollis enim.',
			'Phasellus orci enim, aliquam in congue bibendum, egestas at est.',
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
			'Suspendisse id lorem at dolor iaculis dignissim non quis dui.',
			'Vivamus malesuada tristique odio, id volutpat massa mattis in.',
			'Aliquam sit amet fermentum felis.',
			'Vestibulum sagittis elit eu lacus aliquet sodales.',
			'Nulla in libero augue, eu sodales est.',
			'Etiam ut ligula dolor, ut mattis quam.',
			'Integer urna nulla, luctus quis facilisis eget, dictum sit amet neque.',
			'Aliquam facilisis turpis at tellus tempus euismod.',
			'Cras gravida nulla a sapien rhoncus mollis.',
			'Duis aliquet suscipit quam, vitae cursus nibh egestas at.',
			'Quisque ligula neque, dignissim ac iaculis in, congue ac turpis.',
			'Fusce vitae ante non lectus bibendum eleifend quis quis eros.',
			'Donec vel elementum magna.',
			'Curabitur fermentum orci non tortor consequat quis sollicitudin felis facilisis.',
			'Cras at metus sed nisl pretium malesuada.', 'Suspendisse potenti.',
			'Vestibulum iaculis quam et nibh auctor semper accumsan arcu auctor.',
			'Nullam ultricies, ipsum vitae rhoncus adipiscing, lorem tellus pellentesque felis, eget consequat metus tortor quis massa.',
			'Duis eu tincidunt lorem.',
			'Donec at risus a urna tempor bibendum vitae sed lorem.',
			'Duis pharetra egestas elit ut vehicula.',
			'Aenean posuere tincidunt est, vitae scelerisque leo dignissim at.',
			'Phasellus vitae massa ac odio porta auctor sit amet vitae tellus.',
			'Maecenas consequat fermentum bibendum.',
			'Sed semper velit sit amet lacus commodo pretium.',
			'Maecenas erat leo, ullamcorper vel porttitor a, viverra ut quam.',
			'Donec tincidunt congue vestibulum.',
			'Curabitur nunc orci, euismod id tempor in, pulvinar posuere quam.',
			'Nunc dolor nulla, iaculis id tincidunt sit amet, pretium eget neque.',
			'Praesent fermentum lorem eu justo facilisis at fringilla massa volutpat.',
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
			'Nunc tincidunt facilisis vestibulum.', 'Aliquam erat volutpat.',
			'Nam vitae odio libero, sit amet blandit lorem.',
			'Suspendisse at mauris et erat hendrerit pharetra sed vel magna.',
			'Nullam sodales ornare dolor at pulvinar.',
			'Phasellus bibendum sem vitae augue vehicula et scelerisque ante varius.',
			'Aenean id nulla diam.', 'Aliquam molestie euismod luctus.',
			'Curabitur venenatis, ipsum a semper rhoncus, elit turpis vestibulum felis, quis pulvinar mauris nibh id purus.',
			'In sit amet leo at mauris congue dapibus.',
			'In hac habitasse platea dictumst.', 'Proin nec ullamcorper dolor.',
			'Duis tincidunt, leo congue egestas sollicitudin, ante magna porttitor risus, nec consectetur quam nunc nec quam.',
			'Quisque in accumsan risus.',
			'In vitae ante vel est aliquam venenatis vel vel enim.',
			'Pellentesque pharetra feugiat neque laoreet venenatis.',
			'Maecenas mollis luctus enim, sed vulputate dui facilisis eget.',
			'Aliquam erat volutpat.',
			'In nisl nisl, malesuada sit amet commodo at, varius eget dui.',
			'Donec ornare pharetra pulvinar.', 'Sed ut congue purus.',
			'Aliquam erat volutpat.',
			'Donec massa purus, mattis in posuere vitae, suscipit vitae ante.',
			'Integer a leo ligula, at malesuada lorem.',
			'In erat quam, vestibulum sed pharetra at, ornare eget quam.',
			'Quisque non mi sit amet lacus pretium ornare.',
			'Donec facilisis dapibus vestibulum.',
			'Sed quam justo, mollis quis hendrerit accumsan, egestas ac quam.',
			'Aliquam erat volutpat.',
			'Quisque interdum molestie est molestie dictum.',
			'Duis hendrerit orci non risus dictum vulputate.',
			'Ut tortor metus, faucibus nec sollicitudin non, molestie eu ipsum.',
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
			'Integer quis mauris enim.', 'Curabitur nec mi dui, et dapibus lectus.',
			'Donec mattis diam vitae massa congue a fermentum sem aliquet.',
			'Maecenas vulputate aliquam eleifend.',
			'Maecenas luctus risus a mauris sagittis egestas.',
			'Vivamus bibendum dignissim sapien non accumsan.',
			'Aliquam erat volutpat.',
			'Sed in metus sit amet tellus mollis laoreet.',
			'Nullam egestas volutpat tortor sit amet porta.', 'Nulla facilisi.',
			'Aenean justo justo, sagittis vel pellentesque eu, dictum vel magna.',
			'Quisque sodales imperdiet tristique.',
			'Suspendisse vitae lectus id risus scelerisque gravida.',
			'Cras libero purus, molestie id volutpat nec, fermentum et turpis.',
			'Nunc eget lacus nisl.',
			'Praesent eros magna, pulvinar in tristique a, ullamcorper id lorem.',
			'Ut consectetur nibh at odio lobortis tristique.',
			'Nam vestibulum lacus at nisi laoreet a rutrum tellus euismod.',
			'Aliquam rutrum, est quis malesuada elementum, nulla dui ornare mi, nec volutpat sapien nunc semper nibh.',
			'Pellentesque sed ante velit, a blandit elit.',
			'Quisque interdum, leo sed hendrerit venenatis, massa libero varius ante, vitae posuere ipsum enim et eros.',
			'Etiam at cursus eros.',
			'Nulla adipiscing mauris sed sem dapibus imperdiet.',
			'Mauris ultrices erat non metus auctor quis molestie magna mattis.',
			'Fusce diam nunc, pellentesque quis tempus non, fringilla eget neque.',
			'Pellentesque in odio ac urna eleifend venenatis a sed odio.',
			'Nulla aliquam condimentum aliquet.',
			'Vivamus tempor feugiat purus, in semper est aliquet id.',
			'Pellentesque dolor lacus, dictum sed scelerisque quis, lacinia in sapien.',
			'Vestibulum at elementum dui.',
			'Pellentesque bibendum tortor eu felis lacinia pharetra.',
			'Mauris tempus consequat quam quis sollicitudin.',
			'Proin consequat lobortis mauris, non euismod nisl blandit eu.',
			'Fusce vulputate mi quis nulla fringilla ut accumsan nisl adipiscing.',
			'Aliquam vel diam quis nisi mollis ultricies.',
			'Aliquam erat volutpat.',
			'Pellentesque ornare ornare nibh, dignissim imperdiet libero vestibulum sit amet.',
			'In dui erat, dapibus non posuere quis, egestas nec tortor.',
			'Maecenas a nulla sed eros tincidunt blandit ut eget mauris.',
			'Nam in lorem ac nunc porta congue.',
			'In hac habitasse platea dictumst.',
			'Praesent vitae turpis in nisl sodales tempor.',
			'Suspendisse venenatis leo id diam viverra at aliquam augue dignissim.',
			'Pellentesque tristique lacinia convallis.', 'Vivamus at velit mi.',
			'Vestibulum vehicula volutpat feugiat.', 'Suspendisse potenti.',
			'Quisque in tortor dui, quis sodales ligula.',
			'Phasellus gravida eros eget eros dictum id laoreet turpis accumsan.',
			'Nulla a felis quis nulla sollicitudin congue vel eget tellus.',
			'Suspendisse tincidunt mauris in nisl pharetra eleifend iaculis et lacus.',
			'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras mattis lacus eu metus laoreet vel porttitor leo hendrerit.',
			'Vestibulum nulla neque, varius fermentum semper ut, mattis vitae augue.',
			'Cras varius lacinia auctor.', 'Sed suscipit faucibus tincidunt.',
			'Aenean eget laoreet neque.',
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
			'Phasellus imperdiet, nisi vel elementum porta, ipsum quam ornare magna, ac porta dui urna faucibus quam.',
			'Suspendisse mattis viverra eleifend.', 'Aliquam sed tempor ante.',
			'Vestibulum pretium, nulla nec fringilla dignissim, dolor ligula adipiscing nisi, a lacinia magna dolor eu ligula.',
			'Aenean vitae sodales nisi.',
			'Duis mattis mauris a purus mattis laoreet.',
			'Quisque porta cursus mattis.',
			'Nulla sagittis elit eu libero tempor ultrices.',
			'Ut a ligula sed nunc auctor bibendum.',
			'Suspendisse egestas urna quis urna sodales non accumsan dolor lobortis.',
			'Donec vehicula auctor felis aliquam tincidunt.',
			'Pellentesque ac odio tellus.', 'Suspendisse potenti.',
			'Phasellus laoreet lacus ut justo iaculis sit amet mollis diam rutrum.',
			'Nam vitae consectetur diam.',
			'Maecenas blandit nulla ut dolor lacinia condimentum.',
			'Curabitur varius adipiscing est et porttitor.', 'Sed ac sapien nisl.',
			'Donec fermentum nisl a dui fringilla sollicitudin.',
			'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean gravida auctor pretium.',
			'Nam consequat nunc et dui consectetur posuere.',
			'Fusce adipiscing sem dui.',
			'Maecenas ut mauris iaculis velit porttitor ultrices.',
			'Nulla fermentum tortor et sem laoreet rhoncus.',
			'Mauris in justo eros.',
			'Phasellus dapibus suscipit venenatis.',
			'Nulla viverra ornare tortor, in pulvinar sem mollis nec.',
			'Aliquam vel lacus a ipsum pharetra aliquet.',
			'Nulla commodo risus rhoncus ipsum facilisis posuere.',
			'Sed sem nisi, fringilla ut pharetra id, convallis sit amet nulla.',
			'Mauris neque massa, aliquam in tincidunt in, dignissim a odio.',
			'Nam consequat dapibus erat, eget commodo quam dictum at.',
			'Proin mi ante, feugiat sed suscipit sed, pretium eu dui.',
			'Aenean non augue eget turpis aliquet sagittis.',
			'Nullam placerat lorem ut neque interdum eget blandit risus bibendum.',
			'Praesent convallis tempus justo eu dapibus.',
			'Pellentesque rutrum gravida dui, eget tincidunt erat porta vitae.',
			'Morbi vel justo lacus.',
			'Donec luctus ipsum vel tortor mattis vehicula.',
			'Pellentesque diam nibh, adipiscing eget dapibus ut, iaculis at elit.',
			'Vestibulum gravida varius justo, eget ultricies lectus lobortis ut.',
			'Duis interdum, massa vel tincidunt viverra, est orci dapibus tellus, nec porta metus massa ut leo.',
			'In eget dui nisl, consequat imperdiet enim.',
			'In hac habitasse platea dictumst.',
			'Pellentesque non turpis at nunc viverra auctor.',
			'Aliquam semper ipsum in lectus ornare quis rutrum mauris interdum.',
			'Nulla elementum mollis ipsum eu porta.',
			'Curabitur congue, elit vitae pellentesque vestibulum, mauris quam bibendum diam, nec condimentum mi tellus nec risus.',
			'Morbi in sapien at diam lacinia tempor.',
			'Nam mauris ipsum, placerat sed adipiscing id, iaculis vel orci.',
			'Phasellus mollis quam ac dui adipiscing ullamcorper.',
			'Proin eu lorem sit amet sapien semper varius.',
			'Aenean eget urna sit amet tortor imperdiet lacinia a ac velit.',
			'Phasellus vitae tellus vel neque scelerisque venenatis a nec leo.',
			'Fusce pulvinar malesuada sodales.', 'Duis sit amet leo nisi.',
			'Nunc tempor commodo dolor, eget ultrices justo venenatis tempor.',
			'Nullam tempus urna at urna ultricies vitae faucibus augue viverra.',
			'Nam consectetur erat eget purus cursus non gravida felis venenatis.',
			'Duis vel posuere lacus.',
			'Nam posuere, magna quis fermentum auctor, nisi eros consequat sapien, id auctor orci diam eu neque.',
			'Quisque tincidunt turpis ac lacus porta non venenatis leo pellentesque.',
			'Vivamus dapibus rutrum tempor.',
			'Morbi sagittis nunc non leo molestie in auctor elit aliquet.',
			'Phasellus ante ante, consectetur ut pellentesque quis, porttitor ut metus.',
			'Quisque vitae nibh id ipsum interdum sollicitudin molestie ac libero.',
			'Donec posuere turpis non sem pharetra ullamcorper.',
			'Suspendisse tincidunt quam eu mi auctor vel dictum lorem eleifend.',
			'Aliquam ultricies euismod dolor non commodo.',
			'Integer laoreet leo non lectus porta viverra.',
			'Pellentesque sed libero arcu, sed rhoncus lacus.',
			'Nulla faucibus nibh suscipit lacus euismod eget luctus arcu sollicitudin.',
			'Fusce pharetra laoreet lacus ac faucibus.',
			'Mauris et leo odio, quis molestie urna.',
			'Nam feugiat aliquam bibendum.',
			'Integer eu quam est, sit amet scelerisque felis.',
			'Nunc tincidunt augue felis, ac cursus purus.',
			'Nulla metus diam, venenatis id imperdiet ut, placerat.',
		);
	}

	public static function getLipsum($sentences = 1, $paragraphs = 1) {
		if (self::$_lipsum === null) {
			self::setup();
		}
		$lastLipsum = count(self::$_lipsum) - 1;
		$paras = array();
		$allIndexes = array();
		for ($p = 0; $p < $paragraphs; $p += 1) {
			$paras[$p] = array();
			while (count($paras[$p]) < $sentences) {
				$index = mt_rand(0, $lastLipsum);
				if (!in_array($index, $allIndexes)) {
					$paras[$p][] = $index;
					$allIndexes[] = $index;
				}
			}
		}
		foreach ($paras as &$para) {
			foreach ($para as &$sentence) {
				$sentence = self::$_lipsum[$sentence];
			}
			$para = implode(' ', $para);
		}
		return implode("\n\n", $paras);
	}

}
